_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.12.8
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 55
            "2":
                - 1
                - 5
                - 41
                - 53
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.8
            "5": 0.19.9
            "8":
                - 5
            "12": 0.19.9
            "13": linux-x86_64
augmentation:
    value: normalized-fft
batch_size:
    value: 64
epochs:
    value: 20
fault_type:
    value: cage
learning_rate:
    value: 0.001
model:
    value: DCNN08
